### ISSUE TITLE
Is there a way to have a pattern to match all date format?

### ISSUE THREAD

**Issue by playground** [nlp-compromise/compromise-plugin#2]
I want to do something like this to match mm/dd/yyyy, m/d/yyyy, mm-dd-yyyy & etc.

  "patterns": {
    "/^(\\d{1,2})[-|.|\/](\\d{1,2})[-|.|\/](\\d{4})$/": "Date",
  }

**Comment by spencermountain** [comment]
hey @playground heads up, this repo is deprecated, the current version of the compromise plugin scheme is [here](https://observablehq.com/@spencermountain/compromise-plugins)

yes, you can apply any arbitrary regex using [the match-syntax](https://observablehq.com/@spencermountain/compromise-match-syntax#regex%20mach)
it would look something like this:
```js
let doc = nlp('blah 3/2/2020 foo')
doc.match('/^(\d{1,2})-|.|/-|.|/$/').tag('Date')
doc.debug()
```
cheers
